name: r_finder
description: A campus Lost & Found application designed to replace WhatsApp groups.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.7.0

  # State Management
  provider: ^6.0.0
  
  # Image & ML
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.0
  cached_network_image: ^3.3.0

  # UI
  material_design_icons_flutter: ^7.0.7296
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.0.0
  connectivity_plus: ^5.0.0
  package_info_plus: ^5.0.0

  # HTTP & Serialization
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/rfinder_logo.png
    - assets/images/
    - assets/icons/
